const RAW='https://raw.githubusercontent.com/truquinio/sig-castelldefels/master/data/';
const DATA={pois:null,boundary:null};
const COLORS={'Comercio':'#ff9f68','Restauración':'#42d3a0','Servicios':'#a9d86e','Oficinas':'#bc8cff','Salud':'#ff6b7a','Educación':'#7aa7ff','Ocio y turismo':'#e9c46a','Turismo':'#f4a261','Administración pública':'#8e9df4','Parkings':'#f6c85f','Bicicleta':'#5cc8a1','Deporte y recreación':'#6cc4ff','Cultura':'#f49ac2','Otros servicios':'#a9b6b0'};
const state={selected:null,cats:new Set(Object.keys(COLORS)),search:'',heat:false,ollama:false,norm:null,normKey:'',layers:{poi:true,boundary:true,ortho:false,parcel:false,planning:false},markers:[]};
const map=L.map('map',{preferCanvas:true,zoomControl:true,scrollWheelZoom:true,worldCopyJump:false}).setView([41.2818,1.9825],13.2);
L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap contributors'}).addTo(map);
const boundaryLayer=L.geoJSON(null,{style:{color:'#1f6b59',weight:2,fill:false}}).addTo(map);
const poiLayer=L.layerGroup().addTo(map); const heatLayer=L.layerGroup(); const parcelWms=L.tileLayer.wms('https://ovc.catastro.meh.es/cartografia/INSPIRE/spadgcwms.aspx',{layers:'CP.CadastralParcel',format:'image/png',transparent:true,version:'1.1.1',opacity:.55});
const ortho=L.tileLayer.wms('https://geoserveis.icgc.cat/servei/catalunya/orto-local/wms',{layers:'orto-local-rgb-vigents',format:'image/png',transparent:true,version:'1.1.1',opacity:.78});
const planning=L.tileLayer.wms('https://sig.gencat.cat/ows/PLANEJAMENT/wms',{layers:'PLANEJAMENT',format:'image/png',transparent:true,version:'1.3.0',opacity:.52});
const buildingLayer=L.layerGroup();
function setStatus(t){document.getElementById('status').textContent=t}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function classify(p){const a=(p.amenity||'').toLowerCase(), s=(p.shop||'').toLowerCase(), o=(p.office||'').toLowerCase(), t=(p.tourism||'').toLowerCase(), l=(p.leisure||'').toLowerCase(),tag=(p.primary_tag||'').toLowerCase();
if(a==='hospital'||a==='clinic'||a==='doctors'||a==='dentist'||a==='pharmacy'||/cap|hospital|salut|centre mèdic|centro médico/i.test(p.name||''))return 'Salud';
if(a==='cinema'||a==='theatre'||t==='museum'||t==='attraction'||l==='arts_centre')return 'Ocio y turismo';
if(a==='parking')return 'Parkings';
if(a==='bicycle_parking'||a==='bicycle_rental')return 'Bicicleta';
if(t==='information')return 'Turismo';
if(a==='school'||a==='kindergarten'||a==='college'||a==='university')return 'Educación';
if(a==='townhall'||a==='courthouse'||a==='police'||a==='fire_station'||o==='government')return 'Administración pública';
if(a==='place_of_worship'||a==='library'||l==='library')return 'Cultura';
if(l==='pitch'||l==='sports_centre'||l==='stadium'||l==='track')return 'Deporte y recreación';
if(o)return 'Oficinas';
if(a==='restaurant'||a==='cafe'||a==='fast_food'||a==='bar'||s==='restaurant')return 'Restauración';
if(['beauty','hairdresser','laundry','dry_cleaning','tailor','travel_agency'].includes(s)||/beauty|nails|estética|peluquer/i.test(tag+' '+(p.name||'')))return 'Servicios';
if(s)return 'Comercio';
if(a==='bench'||a==='drinking_water'||a==='toilets'||a==='post_box'||a==='atm')return 'Otros servicios';
return p.category&&COLORS[p.category]?p.category:'Otros servicios';}
function functionalName(p,cat){if(p.name&&p.name.trim()&&p.name.trim().toLowerCase()!=='sin nombre')return p.name;const a=(p.amenity||'').toLowerCase(),s=(p.shop||'').toLowerCase(),o=(p.office||'').toLowerCase(),t=(p.tourism||'').toLowerCase(),l=(p.leisure||'').toLowerCase();const dict={parking:'Parking',bicycle_parking:'Aparcamiento de bicicletas',bicycle_rental:'Punto de alquiler de bicicletas',estate_agent:'Agencia inmobiliaria',seafood:'Pescadería',convenience:'Tienda de conveniencia',kiosk:'Kiosco',beauty:'Centro de estética',pitch:'Pista deportiva',park:'Parque',information:'Señalización turística',cinema:'Cine',restaurant:'Restaurante',cafe:'Cafetería',hairdresser:'Peluquería'};return dict[a]||dict[s]||dict[o]||dict[t]||dict[l]||({Parkings:'Parking',Bicicleta:'Infraestructura ciclista',Turismo:'Señalización turística',Salud:'Centro sanitario',Educación:'Equipamiento educativo',Cultura:'Equipamiento cultural','Deporte y recreación':'Equipamiento deportivo',Oficinas:'Oficina',Servicios:'Servicio',Comercio:'Comercio',Restauración:'Establecimiento de restauración'}[cat]||'Actividad');}
async function fetchJson(url){const r=await fetch(url);if(!r.ok)throw new Error(r.status);return r.json()}
function filtered(){if(!DATA.pois)return [];const q=state.search.toLowerCase();return DATA.pois.features.filter(f=>{const p=f.properties||{},c=classify(p),name=functionalName(p,c).toLowerCase();return state.cats.has(c)&&(!q||name.includes(q)||c.toLowerCase().includes(q)||(p.primary_tag||'').toLowerCase().includes(q));})}
function renderPOIs(){poiLayer.clearLayers();state.markers=[];const fs=filtered();const boundsByCell=new Map();const z=map.getZoom();const cell= z<13 ? .004 : z<14 ? .002 : z<15 ? .001 : 0;
if(cell){fs.forEach(f=>{const [lng,lat]=f.geometry.coordinates;const k=Math.floor(lng/cell)+':'+Math.floor(lat/cell);if(!boundsByCell.has(k))boundsByCell.set(k,[]);boundsByCell.get(k).push(f)});boundsByCell.forEach(items=>{const p=items[0].properties||{}, c=classify(p), center=items.reduce((a,f)=>[a[0]+f.geometry.coordinates[0]/items.length,a[1]+f.geometry.coordinates[1]/items.length],[0,0]);const m=L.circleMarker([center[1],center[0]],{radius:items.length>1?Math.min(20,8+Math.sqrt(items.length)*2):6,weight:1,color:'#07110f',fillColor:COLORS[c],fillOpacity:.9});m.bindPopup(popup(items[0],items.length));m.addTo(poiLayer);});
}else fs.forEach(f=>{const p=f.properties||{},c=classify(p);const [lng,lat]=f.geometry.coordinates;const m=L.circleMarker([lat,lng],{radius:6,weight:1,color:'#07110f',fillColor:COLORS[c],fillOpacity:.9});m.bindPopup(popup(f,1));m.addTo(poiLayer)});
document.getElementById('kpiPoi').textContent=fs.length.toLocaleString('es-ES');document.getElementById('kpiCat').textContent=new Set(fs.map(f=>classify(f.properties||{}))).size;document.getElementById('kpiParking').textContent=DATA.pois?DATA.pois.features.filter(f=>classify(f.properties||{})==='Parkings').length.toLocaleString('es-ES'):'—';renderCategories();renderLegend();}
function popup(f,n){const p=f.properties||{},c=classify(p),name=functionalName(p,c),tag=p.primary_tag||'';return `<div class="popup-card"><h3>${esc(name)}</h3><p><b>${esc(c)}</b>${n>1?` · ${n} elementos agrupados`:''}</p><p class="meta">${esc(tag)} · ${esc(p.osm_id||'')}</p><p class="meta">Fuente: OpenStreetMap</p></div>`}
function renderCategories(){const el=document.getElementById('categoryList');el.innerHTML='';Object.keys(COLORS).forEach(c=>{const count=(DATA.pois?.features||[]).filter(f=>classify(f.properties||{})===c).length;const row=document.createElement('div');row.className='cat-row';row.innerHTML=`<div class="cat-left"><span class="swatch" style="background:${COLORS[c]}"></span>${esc(c)}</div><b>${count}</b>`;row.onclick=()=>{state.cats.has(c)?state.cats.delete(c):state.cats.add(c);renderPOIs()};el.appendChild(row)});}
function renderLegend(){const el=document.getElementById('legendList');el.innerHTML='';Object.keys(COLORS).forEach(c=>{if(!state.cats.has(c))return;const row=document.createElement('div');row.className='legend-row';row.innerHTML=`<div class="legend-left"><span class="swatch" style="background:${COLORS[c]}"></span>${esc(c)}</div>`;el.appendChild(row)})}
function fit(){if(DATA.boundary){const b=boundaryLayer.getBounds();if(b.isValid())map.fitBounds(b,{padding:[30,30]});else map.setView([41.2818,1.9825],13.2)}else map.setView([41.2818,1.9825],13.2)}
async function load(){setStatus('Cargando datos…');try{DATA.boundary=await fetchJson(RAW+'castelldefels_boundary.geojson');boundaryLayer.addData(DATA.boundary);fit();}catch(e){setStatus('Límite remoto no disponible · mapa operativo');}try{DATA.pois=await fetchJson(RAW+'osm_pois_castelldefels.geojson');DATA.pois.features.forEach(f=>{f.properties.category=classify(f.properties||{});f.properties.display_name=functionalName(f.properties||{},f.properties.category);});renderPOIs();setStatus('Mapa operativo · OSM + inventario territorial');}catch(e){setStatus('Mapa base operativo · inventario no disponible');document.getElementById('kpiPoi').textContent='—';}
map.on('zoomend',renderPOIs)}
function toggle(id,on,layer){if(on&&!map.hasLayer(layer))layer.addTo(map);if(!on&&map.hasLayer(layer))map.removeLayer(layer)}
async function catastro(){const rc=document.getElementById('rcInput').value.trim();if(!rc)return;document.getElementById('catastroMsg').textContent='Consultando servicio público…';try{const r=await fetch('/api/catastro?rc='+encodeURIComponent(rc),{signal:AbortSignal.timeout(7000)});if(!r.ok)throw new Error('HTTP '+r.status);const txt=await r.text();const nums=[...txt.matchAll(/<(fxml:)?(superficie|sup)/gi)];const m=txt.match(/<[^>]*sup[^>]*>([0-9.,]+)<\/[^>]*sup[^>]*>/i);const area=m?Number(m[1].replace('.','').replace(',','.')):null;state.selected={rc,site_area:area||null,source:'Catastro OVC'};showParcel();}catch(e){document.getElementById('catastroMsg').textContent='Catastro bloquea la consulta desde GitHub Pages o el servidor no está activo. Ejecutá server.py localmente o abrí el visor oficial.';state.selected={rc,source:'Referencia introducida por usuario'};showParcel();}}
function showParcel(){const p=state.selected||{};document.getElementById('kpiParcel').textContent=p.rc||'—';const card=document.getElementById('parcelCard');card.classList.remove('hidden');card.innerHTML=`<b>Referencia</b> ${esc(p.rc||'—')}<br><span class="mini-note">Superficie: ${p.site_area?Math.round(p.site_area)+' m²':'no obtenida automáticamente'}<br>Fuente: ${esc(p.source||'—')}</span>`;document.getElementById('site').textContent=p.site_area?Math.round(p.site_area)+' m²':'—';}
function zoneGet(){const key=document.getElementById('zoneInput').value.trim();return state.norm?.[key]||null}
function calculate(){const p=state.selected,z=zoneGet();if(!p||!p.site_area||!z||z.edif==null||z.occ==null||z.floors==null||z.height==null){document.getElementById('compliance').className='compliance neutral';document.getElementById('compliance').textContent='Faltan datos de parcela o parámetros normativos verificados.';return null}const max=p.site_area*z.edif,foot=p.site_area*z.occ/100,byFloors=foot*z.floors;const techo=Math.min(max,byFloors);const existing=p.existing_built||0;const pot=techo-existing;const hm2=Number(document.getElementById('homeM2').value)||82;const homes=Math.max(0,Math.floor((techo*(Number(document.getElementById('eff').value)||80)/100)/hm2));document.getElementById('existing').textContent=existing?Math.round(existing)+' m²':'—';document.getElementById('maximum').textContent=Math.round(techo)+' m²';document.getElementById('potential').textContent=(pot>=0?'+':'')+Math.round(pot)+' m²';document.getElementById('calcFloors').textContent=z.floors;document.getElementById('homes').textContent=homes;const c=document.getElementById('compliance');c.className='compliance '+(pot<0?'bad':'ok');c.textContent=pot<0?`El edificio existente supera el máximo teórico en ${Math.round(-pot)} m².`:`Margen teórico disponible: ${Math.round(pot)} m².`;const useful=techo*(Number(document.getElementById('eff').value)||80)/100;const revenue=useful*(Number(document.getElementById('price').value)||0);const cost=techo*(Number(document.getElementById('cost').value)||0);document.getElementById('vUseful').textContent=Math.round(useful).toLocaleString('es-ES')+' m²';document.getElementById('vRevenue').textContent=Math.round(revenue).toLocaleString('es-ES')+' €';document.getElementById('vCost').textContent=Math.round(cost).toLocaleString('es-ES')+' €';document.getElementById('vMargin').textContent=Math.round(revenue-cost).toLocaleString('es-ES')+' €';return {max,foot,techo,pot,homes,useful,revenue,cost};}
async function loadNorm(){try{const r=await fetch('./data/normative_registry.json');state.norm=await r.json();document.getElementById('normSource').textContent='Fuente: registro normativo local';}catch{state.norm={};document.getElementById('normSource').textContent='Fuente: no verificada · agregá reglas';}}
function saveZone(){const key=document.getElementById('zoneInput').value.trim();if(!key)return;state.norm=state.norm||{};state.norm[key]={edif:num('edif'),occ:num('occ'),floors:num('floors'),height:num('height'),setback:num('setback'),m2home:num('m2home'),source:'Introducido por usuario',verified:false};localStorage.setItem('sig_norm',JSON.stringify(state.norm));document.getElementById('normSource').textContent='Fuente: usuario · NO verificado';calculate();}
function num(id){const v=document.getElementById(id).value;return v===''?null:Number(v)}
function scenario(){const r=calculate();if(!r||!state.selected)return;const center=map.getCenter();const z=zoneGet();buildingLayer.clearLayers();const lat=center.lat,lon=center.lng;const d=Math.sqrt(r.foot);const dlat=d/111000/2,dlon=d/(111000*Math.cos(lat*Math.PI/180))/2;const poly=[[lat-dlat,lon-dlon],[lat-dlat,lon+dlon],[lat+dlat,lon+dlon],[lat+dlat,lon-dlon]];const layer=L.polygon(poly,{color:'#31d29e',weight:2,fillColor:'#31d29e',fillOpacity:.18});layer.bindPopup(`<div class="popup-card"><h3>Volumen teórico</h3><p>${Math.round(r.techo)} m² techo</p><p>${z.floors} plantas · ${z.height} m</p><p class="meta">Escenario analítico, no licencia.</p></div>`);layer.addTo(buildingLayer);buildingLayer.addTo(map);open3D(r,z);setStatus('Escenario conceptual generado');}

let threeRenderer,threeScene,threeCamera,threeAnim;
function open3D(r,z){
 const modal=document.getElementById('threeModal'); modal.classList.remove('hidden');
 const host=document.getElementById('threeScene'); host.innerHTML='';
 const info=document.getElementById('threeInfo'); info.textContent=`${Math.round(r.techo).toLocaleString('es-ES')} m² techo · ${z.floors} plantas · ${z.height} m · volumen conceptual`;
 const script=document.createElement('script'); script.src='https://unpkg.com/three@0.160.0/build/three.min.js'; script.onload=()=>renderThree(r,z,host); document.head.appendChild(script);
}
function renderThree(r,z,host){
 const T=window.THREE; if(!T)return; if(threeAnim)cancelAnimationFrame(threeAnim);
 threeScene=new T.Scene(); threeScene.background=new T.Color(0x07110f); const w=host.clientWidth||800,h=host.clientHeight||520;
 threeCamera=new T.PerspectiveCamera(45,w/h,.1,1000); threeCamera.position.set(7,7,9); threeCamera.lookAt(0,2,0);
 threeRenderer=new T.WebGLRenderer({antialias:true}); threeRenderer.setSize(w,h); host.appendChild(threeRenderer.domElement);
 threeScene.add(new T.AmbientLight(0xffffff,1.4)); const dl=new T.DirectionalLight(0xffffff,1.8); dl.position.set(5,10,6); threeScene.add(dl);
 const root=new T.Group(); const footprint=Math.max(4,Math.sqrt(r.foot)/6); const floorH=Math.max(1.8,z.height/Math.max(1,z.floors));
 for(let i=0;i<Math.max(1,z.floors);i++){const g=new T.BoxGeometry(footprint, floorH*.92, footprint);const m=new T.MeshStandardMaterial({color:0x55d8b0,transparent:true,opacity:.78});const mesh=new T.Mesh(g,m);mesh.position.y=i*floorH+floorH/2;root.add(mesh)}
 const base=new T.GridHelper(Math.max(16,footprint*3),16,0x294e43,0x153128);root.add(base);threeScene.add(root);
 let dragging=false,lastX=0;host.onmousedown=e=>{dragging=true;lastX=e.clientX};host.onmouseup=()=>dragging=false;host.onmouseleave=()=>dragging=false;host.onmousemove=e=>{if(dragging){root.rotation.y+=(e.clientX-lastX)*.01;lastX=e.clientX}};host.onwheel=e=>{threeCamera.position.z=Math.max(4,Math.min(18,threeCamera.position.z+e.deltaY*.01));threeCamera.position.y=Math.max(3,Math.min(14,threeCamera.position.y+e.deltaY*.005));threeCamera.lookAt(0,2,0);e.preventDefault()};
 const animate=()=>{threeAnim=requestAnimationFrame(animate);root.rotation.y+=.002;threeRenderer.render(threeScene,threeCamera)};animate();
}

function answer(q){q=q.toLowerCase();if(/catastro|referencia|parcela/.test(q))return state.selected?`Parcela ${state.selected.rc}. Superficie ${state.selected.site_area?Math.round(state.selected.site_area)+' m²':'no disponible'}. Fuente: ${state.selected.source||'usuario'}.`:'No hay una parcela cargada.';if(/normativa|permit|edific|altura|planta/.test(q)){const k=document.getElementById('zoneInput').value.trim();const z=zoneGet();return z?`Clave ${k}: edificabilidad ${z.edif??'—'}, ocupación ${z.occ??'—'}%, ${z.floors??'—'} plantas, altura ${z.height??'—'} m. Estado: ${z.verified?'verificado':'no verificado'}.`:'No hay una regla cargada.';}if(/parking/.test(q))return `Parkings en el inventario: ${DATA.pois?.features.filter(f=>classify(f.properties||{})==='Parkings').length||0}.`;if(/bicicleta/.test(q))return `Infraestructura ciclista: ${DATA.pois?.features.filter(f=>classify(f.properties||{})==='Bicicleta').length||0} registros.`;return `Puedo analizar ${filtered().length} registros visibles, la parcela cargada y la clave urbanística seleccionada.`;}
async function ask(){const q=document.getElementById('ask').value.trim();if(!q)return;let a=answer(q);if(state.ollama){try{const r=await fetch('http://localhost:11434/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:'qwen2.5:3b',stream:false,messages:[{role:'system',content:'Eres agente SIG municipal. Usa solo contexto. No inventes. Distingue oficial, abierto, inferencia y escenario.'},{role:'user',content:`Pregunta: ${q}\nContexto: ${JSON.stringify({parcel:state.selected,zone:zoneGet(),visible:filtered().length})}`}]})});if(r.ok){const j=await r.json();a=j.message?.content||a;}}catch{}}document.getElementById('answer').textContent=a}
function report(){const data={generated:new Date().toISOString(),parcel:state.selected,visible:filtered().length,categories:[...new Set(filtered().map(f=>classify(f.properties||{})))],normative:zoneGet()||null};const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='sig-castelldefels-digital-twin-analysis.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function openCatastro(){const rc=document.getElementById('rcInput').value.trim();window.open('https://www1.sedecatastro.gob.es/Cartografia/mapa.aspx?buscar='+encodeURIComponent(rc||'S'),'_blank','noopener')}
document.getElementById('fitBtn').onclick=fit;document.getElementById('satBtn').onclick=()=>toggle('orthoBtn',true,ortho);document.getElementById('parcelBtn').onclick=()=>toggle('parcelBtn',true,parcelWms);document.getElementById('planBtn').onclick=()=>toggle('planBtn',true,planning);document.getElementById('reportBtn').onclick=report;document.getElementById('catastroBtn').onclick=catastro;document.getElementById('catastroOpenBtn').onclick=openCatastro;document.getElementById('saveZoneBtn').onclick=saveZone;document.getElementById('scenarioBtn').onclick=scenario;document.getElementById('close3d').onclick=()=>document.getElementById('threeModal').classList.add('hidden');document.getElementById('askBtn').onclick=ask;document.getElementById('ollamaBtn').onclick=async()=>{try{const r=await fetch('http://localhost:11434/api/tags',{signal:AbortSignal.timeout(2000)});if(!r.ok)throw 0;state.ollama=true;document.getElementById('aiStatus').textContent='Ollama conectada';}catch{state.ollama=false;document.getElementById('aiStatus').textContent='Determinista · sin API';}};document.getElementById('search').oninput=e=>{state.search=e.target.value;renderPOIs()};document.getElementById('poiLayer').onchange=e=>toggle('',e.target.checked,poiLayer);document.getElementById('boundaryLayer').onchange=e=>toggle('',e.target.checked,boundaryLayer);document.getElementById('heatLayer').onchange=e=>{state.heat=e.target.checked;};document.getElementById('buildingLayer').onchange=e=>toggle('',e.target.checked,buildingLayer);['price','cost','eff','homeM2'].forEach(id=>document.getElementById(id).oninput=calculate);document.getElementById('rcInput').onkeydown=e=>{if(e.key==='Enter')catastro()};document.getElementById('zoneInput').onkeydown=e=>{if(e.key==='Enter')saveZone()};loadNorm().then(()=>{try{const saved=JSON.parse(localStorage.getItem('sig_norm')||'null');if(saved)state.norm=saved;}catch{}});load();
