const RAW='https://raw.githubusercontent.com/truquinio/sig-castelldefels/master/data/';
const DATA={pois:null,boundary:null,parcel:null,muc:null};
const COLORS={
 'Comercio':'#ff9f68','Restauración':'#42d3a0','Servicios':'#a9d86e','Oficinas':'#bc8cff','Salud':'#ff6b7a','Educación':'#7aa7ff','Ocio y turismo':'#e9c46a','Turismo':'#f4a261','Administración pública':'#8e9df4','Parkings':'#f6c85f','Bicicleta':'#5cc8a1','Deporte y recreación':'#6cc4ff','Otros servicios':'#a9b6b0'
};
const state={q:'',cats:new Set(),threeD:false,ortho:false,norm:false,parcelLayer:false,planningLayer:false,selected:null,ai:false,aiMode:'deterministic',styleFallback:false};
const ZONES={
 '13b':{edif:null,occ:null,floors:null,height:null,setback:null,m2home:80,label:'13b · densificació urbana semiintensiva',sourceType:'municipal',source:'PGM Castelldefels / modificacions 2012 i 2020 · validar condicionants de parcel·la'},
 '20a/7':{edif:0.75,occ:30,floors:3,height:9.45,setback:4,m2home:80,label:'20a/7 · plurifamiliar aïllada',sourceType:'reference',source:'NNUU/OME · paràmetres incorporats com a referència, validar expedient'},
 '20a/8':{edif:1.5,occ:30,floors:4,height:16.7,setback:4,m2home:80,label:'20a/8 · plurifamiliar aïllada',sourceType:'reference',source:'NNUU/OME · paràmetres incorporats com a referència, validar expedient'},
 '20a/9':{edif:1.0,occ:30,floors:3,height:13.65,setback:3,m2home:80,label:'20a/9 · plurifamiliar aïllada',sourceType:'reference',source:'PGM/OME · validar condicions específiques'},
 '20a/9u':{edif:1.0,occ:40,floors:3,height:9.45,setback:3,m2home:80,label:'20a/9u · unifamiliar aïllada',sourceType:'reference',source:'Documentació pública · validar expedient vigent'},
 '20a/10':{edif:0.75,occ:30,floors:3,height:9.45,setback:3,m2home:80,label:'20a/10 · unifamiliar aïllada',sourceType:'reference',source:'Documentació pública · validar expedient vigent'},
 '20a/11':{edif:0.5,occ:20,floors:2,height:7.0,setback:5,m2home:80,label:'20a/11 · unifamiliar aïllada',sourceType:'reference',source:'NNUU/OME · validar expedient vigent'},
 '20a/12':{edif:0.35,occ:10,floors:2,height:7.0,setback:5,m2home:80,label:'20a/12 · unifamiliar aïllada',sourceType:'reference',source:'NNUU/OME · validar expedient vigent'}
};
const FALLBACK_STYLE={version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]};
const map=new maplibregl.Map({container:'map',style:'https://tiles.openfreemap.org/styles/liberty',center:[1.982,41.281],zoom:13.1,pitch:0,bearing:0,antialias:true,failIfMajorPerformanceCaveat:false});
map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),'top-right');
map.on('load',async()=>{setStatus('Cargando datos…');await loadData();setupLayers();initZones();render();await refreshExternalLayers();fitMunicipality();setStatus(state.styleFallback?'Listo · mapa OSM de respaldo':'Listo · gemelo digital');});
map.on('error',()=>{if(!state.styleFallback){state.styleFallback=true;try{map.setStyle(FALLBACK_STYLE);}catch(_){} }});
map.on('styledata',()=>{if(state.threeD) add3DBuildings();});
async function fetchJSON(url){const r=await fetch(url);if(!r.ok)throw new Error(`${r.status} ${url}`);return r.json();}
async function loadData(){try{DATA.pois=await fetchJSON(RAW+'osm_pois_castelldefels.geojson');DATA.boundary=await fetchJSON(RAW+'castelldefels_boundary.geojson');normalizePOIs();}catch(e){setStatus('No se pudieron cargar los datos base');console.error(e);}}
function normalizePOIs(){const cats=new Set();DATA.pois.features.forEach(f=>{const p=f.properties||{};p.category=normalizeCategory(p);p.display_name=displayName(p);p.name_quality=cleanName(p.name)?'Fuente OSM':'Nombre funcional';f.properties=p;cats.add(p.category);});state.cats=new Set(cats);document.getElementById('kpi-cats').textContent=cats.size;}
function cleanName(v){const x=String(v??'').trim();return x&&!/^sin nombre$/i.test(x)&&!/^unnamed$/i.test(x)?x:'';}
function displayName(p){const real=cleanName(p.name);if(real)return real;const tag=String(p.primary_tag||'').toLowerCase();const names={'amenity=parking':'Parking','amenity=bicycle_parking':'Aparcamiento de bicicletas','amenity=bicycle_rental':'Punto de alquiler de bicicletas','leisure=park':'Parque','leisure=playground':'Área de juegos','leisure=pitch':'Pista deportiva','office=estate_agent':'Agencia inmobiliaria','shop=seafood':'Pescadería','shop=convenience':'Tienda de conveniencia','shop=kiosk':'Kiosco','shop=beauty':'Centro de estética','tourism=information':'Punto de información turística','amenity=cinema':'Cine'};if(names[tag])return names[tag];return tag.replace(/^[^=]+=/,'').replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase())||'Punto cartográfico';}
function normalizeCategory(p){const tag=String(p.primary_tag||'').toLowerCase();const name=String(p.name||'').toLowerCase();const s=`${name} ${tag} ${p.subcategory||''} ${p.type||''}`.toLowerCase();if(/cap\b|centro de salud|ambulatorio|clinic|hospital|medical|dent|farmac|salud/.test(s))return 'Salud';if(/office=|office |gestor|consultor|inmobiliaria|inmobiliario/.test(s))return 'Oficinas';if(/amenity=parking|parking|car_park/.test(tag))return 'Parkings';if(/bicycle_rental|bicycle_share|bicycle_parking/.test(tag))return 'Bicicleta';if(/school|colegio|escol|institut|univers|education/.test(s))return 'Educación';if(/government|townhall|police|fire_station|public_service/.test(s))return 'Administración pública';if(/cinema|cine|museum|museo|theatre|teatro|culture|cultural|library|biblioteca|leisure=park|leisure=playground|leisure=pitch|sport|gym|stadium|recreation/.test(s))return 'Ocio y turismo';if(/tourism=|tourist|hotel|hostel|camping|information/.test(s)&&!/(parking|bike)/.test(s))return 'Turismo';if(/beauty|hairdresser|salon|service|repair|laundry|dry_clean/.test(s))return 'Servicios';if(/restaurant|cafe|bar|fast_food|bakery|ice_cream/.test(s))return 'Restauración';if(/shop=|shop |retail|supermarket|store|mall|boutique|commercial/.test(s))return 'Comercio';return 'Otros servicios';}
function setupLayers(){if(map.getSource('boundary'))return;map.addSource('boundary',{type:'geojson',data:DATA.boundary});map.addLayer({id:'boundary',type:'line',source:'boundary',paint:{'line-color':'#76e3bd','line-width':2,'line-opacity':.9}});map.addSource('pois',{type:'geojson',data:{type:'FeatureCollection',features:[]},cluster:true,clusterMaxZoom:16,clusterRadius:44});map.addLayer({id:'pois-clusters',type:'circle',source:'pois',filter:['has','point_count'],paint:{'circle-radius':['step',['get','point_count'],15,10,19,50,25],'circle-color':'#6fae99','circle-opacity':.92,'circle-stroke-color':'#07110e','circle-stroke-width':1.2}});map.addLayer({id:'pois-cluster-count',type:'symbol',source:'pois',filter:['has','point_count'],layout:{'text-field':['get','point_count_abbreviated'],'text-size':11},paint:{'text-color':'#07110e'}});map.addLayer({id:'pois',type:'circle',source:'pois',filter:['!',['has','point_count']],paint:{'circle-radius':['interpolate',['linear'],['zoom'],10,3,16,7],'circle-color':['match',['get','category'],...Object.entries(COLORS).flat(),'#aaa'],'circle-stroke-color':'#06120e','circle-stroke-width':1,'circle-opacity':.9}});map.on('click','pois',e=>popup(e.features[0]));map.on('click','pois-clusters',e=>{const f=map.queryRenderedFeatures(e.point,{layers:['pois-clusters']})[0];if(f)map.getSource('pois').getClusterExpansionZoom(f.properties.cluster_id,(err,z)=>{if(!err)map.easeTo({center:f.geometry.coordinates,zoom:z});});});map.addSource('ortho',{type:'raster',tiles:['https://geoserveis.icgc.cat/servei/catalunya/orto-local/wms?service=WMS&version=1.1.1&request=GetMap&layers=orto-local-rgb-vigents&styles=&format=image/png&transparent=true&srs=EPSG:3857&width=256&height=256&bbox={bbox-epsg-3857}'],tileSize:256});map.addLayer({id:'ortho',type:'raster',source:'ortho',paint:{'raster-opacity':.8}});map.setLayoutProperty('ortho','visibility','none');}
function add3DBuildings(){if(map.getLayer('3d-buildings'))return;const c=map.getStyle().layers?.find(l=>/building/i.test(l.id)&&l.type==='fill');if(!c)return;try{map.addLayer({id:'3d-buildings',type:'fill-extrusion',source:c.source,'source-layer':c['source-layer'],minzoom:13,paint:{'fill-extrusion-color':'#527d6d','fill-extrusion-height':['coalesce',['get','render_height'],['get','height'],10],'fill-extrusion-base':['coalesce',['get','render_min_height'],['get','min_height'],0],'fill-extrusion-opacity':.66}},c.id);map.setLayoutProperty('3d-buildings','visibility',state.threeD?'visible':'none');}catch(e){console.warn('3D',e);}}
function render(){if(!DATA.pois)return;const fs=getFiltered();map.getSource('pois').setData({type:'FeatureCollection',features:fs});document.getElementById('kpi-poi').textContent=fs.length.toLocaleString('es-ES');document.getElementById('kpi-parking').textContent=DATA.pois.features.filter(f=>f.properties.category==='Parkings').length.toLocaleString('es-ES');buildCategories();updateLegend();updateViability();}
function getFiltered(){return DATA.pois.features.filter(f=>{const p=f.properties||{};const txt=`${p.display_name||p.name||''} ${p.category||''} ${p.primary_tag||''}`.toLowerCase();return state.cats.has(p.category)&&(!state.q||txt.includes(state.q));});}
function buildCategories(){const counts={};DATA.pois.features.forEach(f=>counts[f.properties.category]=(counts[f.properties.category]||0)+1);const el=document.getElementById('category-list');el.innerHTML='';Object.entries(counts).sort((a,b)=>b[1]-a[1]).forEach(([c,n])=>{const d=document.createElement('div');d.className='cat';d.innerHTML=`<div class="left"><span class="dot" style="background:${COLORS[c]||'#aaa'}"></span><span>${escapeHtml(c)}</span></div><span class="count">${n}</span>`;d.onclick=()=>{state.cats.has(c)?state.cats.delete(c):state.cats.add(c);render();};el.append(d);});}
function updateLegend(){const c={};DATA.pois.features.forEach(f=>{const k=f.properties.category;c[k]=(c[k]||0)+1;});document.getElementById('legend').innerHTML='<div class="legend-title">Leyenda de categorías</div>'+Object.entries(c).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="legend-row"><span><span class="dot" style="background:${COLORS[k]||'#aaa'}"></span>${escapeHtml(k)}</span><span>${v}</span></div>`).join('');}
function popup(f){const p=f.properties;new maplibregl.Popup({offset:12,maxWidth:'380px'}).setLngLat(f.geometry.coordinates).setHTML(`<div class="popup-title">${escapeHtml(p.display_name||'Punto')}</div><div class="popup-meta">${escapeHtml(p.category||'')} · ${escapeHtml(p.primary_tag||'')}</div><div class="popup-note"><b>${escapeHtml(p.name_quality||'')}</b><br>Fuente primaria: OpenStreetMap.${p.name_quality==='Nombre funcional'?'<br>Denominación funcional: no se encontró nombre público en OSM.':''}</div>`).addTo(map);}
function initZones(){const s=document.getElementById('zone-select');s.innerHTML='';Object.entries(ZONES).forEach(([k,z])=>{const o=document.createElement('option');o.value=k;o.textContent=z.label;s.append(o);});s.value='20a/10';const saved=localStorage.getItem('sigcf-zones');if(saved)try{Object.assign(ZONES,JSON.parse(saved));}catch{}loadZoneFields();s.onchange=loadZoneFields;document.getElementById('btn-save-zone').onclick=()=>{const z=ZONES[s.value];[['n-edif','edif'],['n-occ','occ'],['n-floors','floors'],['n-height','height'],['n-setback','setback'],['n-m2home','m2home']].forEach(([id,k])=>z[k]=number(id));z.sourceType='user';z.source='Paràmetre introduït/modificat localment · validar contra normativa oficial';localStorage.setItem('sigcf-zones',JSON.stringify(ZONES));loadZoneFields();};document.getElementById('btn-reset-zone').onclick=()=>loadZoneFields();}
function loadZoneFields(){const z=ZONES[document.getElementById('zone-select').value];[['n-edif',z.edif],['n-occ',z.occ],['n-floors',z.floors],['n-height',z.height],['n-setback',z.setback],['n-m2home',z.m2home]].forEach(([id,v])=>document.getElementById(id).value=v??'');document.getElementById('norm-source').textContent=`Fuente: ${z.source}`;document.getElementById('kpi-zone').textContent=document.getElementById('zone-select').value;updateViability();}
function number(id){const v=parseFloat(document.getElementById(id).value);return Number.isFinite(v)?v:null;}
function updateViability(){const p=state.selected,z=ZONES[document.getElementById('zone-select').value],site=p?.site_area??null;const existing=p?.existing_built??null;const max=z.edif&&site?site*z.edif:null;document.getElementById('c-site').textContent=site?`${Math.round(site).toLocaleString('es-ES')} m²`:'—';document.getElementById('c-existing').textContent=existing?`${Math.round(existing).toLocaleString('es-ES')} m²`:'—';document.getElementById('c-max').textContent=max?`${Math.round(max).toLocaleString('es-ES')} m²`:'—';document.getElementById('c-potential').textContent=max!=null&&existing!=null?`${Math.round(max-existing).toLocaleString('es-ES')} m²`:'—';document.getElementById('c-floors').textContent=z.floors??'—';document.getElementById('c-homes').textContent=max&&z.m2home?Math.floor(max/z.m2home):'—';const comp=document.getElementById('compliance');if(!site) {comp.className='compliance neutral';comp.textContent='Seleccioná una parcela catastral para comparar existente y máximo teórico.';} else if(z.edif==null||z.occ==null||z.floors==null||z.height==null){comp.className='compliance neutral';comp.textContent='La clave seleccionada no tiene parámetros suficientes para un cálculo normativo fiable.';} else if(existing!=null&&max<existing){comp.className='compliance warn';comp.textContent='⚠ El construido supera el máximo teórico de la clave cargada. Revisar planeamiento aplicable y situación existente.';} else {comp.className='compliance ok';comp.textContent='✓ Compatible con los parámetros cargados, de forma preliminar. No sustituye informe urbanístico.';}const eff=number('eff')||80,price=number('price')||0,cost=number('cost')||0,useful=max?max*eff/100:null,revenue=useful?useful*price:null,build=max?max*cost:null;document.getElementById('v-useful').textContent=useful?`${Math.round(useful).toLocaleString('es-ES')} m²`:'—';document.getElementById('v-revenue').textContent=revenue?formatEur(revenue):'—';document.getElementById('v-cost').textContent=build?formatEur(build):'—';document.getElementById('v-margin').textContent=revenue!=null&&build!=null?formatEur(revenue-build):'—';}
function formatEur(n){return new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);}
function toggle3D(force){state.threeD=force??!state.threeD;map.setPitch(state.threeD?60:42);if(map.getLayer('3d-buildings'))map.setLayoutProperty('3d-buildings','visibility',state.threeD?'visible':'none');document.getElementById('layer-3d').checked=state.threeD;add3DBuildings();}
function toggleOrtho(force){state.ortho=force??!state.ortho;map.setLayoutProperty('ortho','visibility',state.ortho?'visible':'none');document.getElementById('layer-ortho').checked=state.ortho;}
function fitMunicipality(){if(DATA.boundary?.features?.length){const b=new maplibregl.LngLatBounds();const walk=g=>{if(!g)return;if(g.type==='Point')b.extend(g.coordinates);else if(g.coordinates)g.coordinates.forEach(walk)};DATA.boundary.features.forEach(f=>walk(f.geometry));if(!b.isEmpty())map.fitBounds(b,{padding:30,duration:700});}}
async function consultCatastro(){const rc=document.getElementById('rc-input').value.trim().toUpperCase().replace(/\s/g,'');if(!/^[A-Z0-9]{14}(?:[A-Z0-9]{4}|[A-Z0-9]{6})?$/.test(rc)){setCatStatus('Referencia no válida. Usá 14, 18 o 20 posiciones.');return;}setCatStatus('Consultando Catastro…');try{const text=await catastroRequest(rc);const parsed=parseCatastro(text,rc);state.selected=parsed;showCatastro(parsed);updateViability();setCatStatus('✓ Catastro consultado.');if(parsed.coords){map.flyTo({center:parsed.coords,zoom:18,pitch:58,duration:1200});addSelectedParcel(parsed);}else{setCatStatus('✓ Datos recibidos; coordenadas no disponibles en la respuesta.');}document.getElementById('kpi-parcel').textContent=rc.slice(0,14);}catch(e){console.error(e);setCatStatus('No se pudo consultar desde este navegador. Usá el botón Mapa o el script local scripts/catastro_fetch.py.');}}
async function catastroRequest(rc){const url=`/api/catastro?rc=${encodeURIComponent(rc)}`;try{const r=await fetch(url);if(r.ok)return r.text();}catch{}const direct=`https://ovc.catastro.meh.es/ovcservweb/ovcswlocalizacionrc/ovccallejero.asmx/Consulta_DNPRC?Provincia=Barcelona&Municipio=Castelldefels&RC=${encodeURIComponent(rc)}`;const r=await fetch(direct,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error(r.status);return r.text();}
function parseCatastro(xml,rc){const doc=new DOMParser().parseFromString(xml,'text/xml');const txt=n=>doc.getElementsByTagName(n)[0]?.textContent?.trim()||'';const nums=[...doc.getElementsByTagName('supconst')].map(x=>parseFloat(x.textContent)).filter(Number.isFinite);const elems=[...doc.querySelectorAll('lcsd, elem, csd')];let built=0,res=0,comm=0,park=0,units=0;const uses=[];for(const x of elems){const u=(x.querySelector('lcuso, uso')?.textContent||'').trim();const s=parseFloat(x.querySelector('sconstruida, superficie')?.textContent||'');if(Number.isFinite(s)){built+=s;uses.push({use:u,area:s});if(/resid/i.test(u))res+=s;if(/comerc/i.test(u))comm+=s;if(/almac|garaje|aparc/i.test(u))park+=s;if(/resid/i.test(u)&&/vivienda/i.test(u))units++;}}const sfc=parseFloat(txt('sfc')||txt('supfinca')||txt('superficie'));let coords=null;const x=txt('xcen'),y=txt('ycen');if(x&&y)coords=[+x,+y];return{rc,site_area:Number.isFinite(sfc)?sfc:null,existing_built:built||nums.reduce((a,b)=>a+b,0)||null,residential:res||null,commercial:comm||null,parking:park||null,units:units||null,year:txt('antiguedad')||null,address:txt('ldt')||'Catastro',coords,uses};}
function showCatastro(d){const el=document.getElementById('catastro-result');el.classList.remove('hidden');el.innerHTML=`<div class="result-title">Ficha catastral</div><div class="compare-grid"><div><span>Referencia</span><strong>${escapeHtml(d.rc)}</strong></div><div><span>Superficie</span><strong>${d.site_area?Math.round(d.site_area)+' m²':'—'}</strong></div><div><span>Construido</span><strong>${d.existing_built?Math.round(d.existing_built)+' m²':'—'}</strong></div><div><span>Viviendas</span><strong>${d.units??'—'}</strong></div></div><div class="mini-note">${escapeHtml(d.address||'')} · Datos catastrales no protegidos</div>`;}
function setCatStatus(t){document.getElementById('catastro-status').textContent=t;}
function openCatastroMap(){const rc=document.getElementById('rc-input').value.trim();window.open(`https://www1.sedecatastro.gob.es/Cartografia/mapa.aspx?buscar=S&rc=${encodeURIComponent(rc)}`,'_blank');}
function addSelectedParcel(d){if(!d.coords)return;const fc={type:'FeatureCollection',features:[{type:'Feature',properties:{rc:d.rc,name:d.address||d.rc},geometry:{type:'Point',coordinates:d.coords}}]};if(map.getSource('selected-parcel'))map.getSource('selected-parcel').setData(fc);else{map.addSource('selected-parcel',{type:'geojson',data:fc});map.addLayer({id:'selected-parcel',type:'circle',source:'selected-parcel',paint:{'circle-radius':9,'circle-color':'#ffffff','circle-opacity':.08,'circle-stroke-color':'#ffffff','circle-stroke-width':2.5}});}}
function generateNormative(){const p=state.selected,z=ZONES[document.getElementById('zone-select').value];if(!p?.site_area||!z.edif||!z.occ||!z.floors||!z.height){setStatus('Faltan parámetros normativos o parcela para generar el volumen.');return;}const footprint=Math.min(p.site_area*z.occ/100,p.site_area*z.edif/z.floors);const max=p.site_area*z.edif;const usable=Math.max(0,Math.min(footprint*z.floors,max));const half=Math.sqrt(footprint)/2;state.normData={site:p.site_area,footprint,max,usable,height:z.height,floors:z.floors,setback:z.setback};drawNormative(p.coords||[1.982,41.281]);toggle3D(true);document.getElementById('layer-norm').checked=true;state.norm=true;document.getElementById('norm-summary').textContent=`Volumen conceptual: ${Math.round(footprint)} m² de huella · ${z.floors} plantas · ${z.height} m · ${Math.round(usable)} m² techo teórico utilizado.`;setStatus('Volumen normativo preliminar generado.');}
function drawNormative(center){if(!state.normData)return;const n=state.normData;const half=Math.sqrt(n.footprint)/111000/2;const lon=half/Math.cos(center[1]*Math.PI/180);const lat=half;const base=[[center[0]-lon,center[1]-lat],[center[0]+lon,center[1]-lat],[center[0]+lon,center[1]+lat],[center[0]-lon,center[1]+lat],[center[0]-lon,center[1]-lat]];const fc={type:'FeatureCollection',features:[{type:'Feature',properties:{height:n.height,floors:n.floors},geometry:{type:'Polygon',coordinates:[base]}}]};if(map.getSource('norm'))map.getSource('norm').setData(fc);else{map.addSource('norm',{type:'geojson',data:fc});map.addLayer({id:'norm',type:'fill-extrusion',source:'norm',paint:{'fill-extrusion-color':'#6de1b5','fill-extrusion-height':n.height,'fill-extrusion-base':0,'fill-extrusion-opacity':.58}});}}
async function refreshExternalLayers(){document.getElementById('external-status').textContent='Fuentes externas listas: Catastro WFS/OVC · MUC/Planeamiento · ICGC · Overture.';}
async function togglePlanning(){state.planningLayer=!state.planningLayer;document.getElementById('layer-planning').checked=state.planningLayer;if(!state.planningLayer){if(map.getLayer('planning'))map.setLayoutProperty('planning','visibility','none');return;}if(!map.getSource('planning')){let layer='';try{const r=await fetch('/api/muc/capabilities');if(r.ok){const xml=await r.text();const doc=new DOMParser().parseFromString(xml,'text/xml');const ls=[...doc.getElementsByTagName('Layer')];const cand=ls.map(x=>({name:x.getElementsByTagName('Name')[0]?.textContent?.trim()||'',title:x.getElementsByTagName('Title')[0]?.textContent?.trim()||''})).filter(x=>x.name);layer=(cand.find(x=>/planej|urban|qualific|muc/i.test(x.title))||cand[0])?.name||'';}}catch(e){}if(!layer)layer='PLANEJAMENT';const url=`https://sig.gencat.cat/ows/PLANEJAMENT/wms?service=WMS&version=1.3.0&request=GetMap&layers=${encodeURIComponent(layer)}&styles=&format=image/png&transparent=true&crs=EPSG:3857&width=256&height=256&bbox={bbox-epsg-3857}`;map.addSource('planning',{type:'raster',tiles:[url],tileSize:256});map.addLayer({id:'planning',type:'raster',source:'planning',paint:{'raster-opacity':.58}});}else map.setLayoutProperty('planning','visibility','visible');}
function toggleParcelLayer(){state.parcelLayer=!state.parcelLayer;document.getElementById('layer-parcels').checked=state.parcelLayer;const url='https://ovc.catastro.meh.es/cartografia/INSPIRE/spadgcwms.aspx?service=WMS&version=1.1.1&request=GetMap&layers=CP.CadastralParcel&styles=&format=image/png&transparent=true&srs=EPSG:3857&width=256&height=256&bbox={bbox-epsg-3857}';if(!map.getSource('cad-parcels')){map.addSource('cad-parcels',{type:'raster',tiles:[url],tileSize:256});map.addLayer({id:'cad-parcels',type:'raster',source:'cad-parcels',paint:{'raster-opacity':.55}});}map.setLayoutProperty('cad-parcels','visibility',state.parcelLayer?'visible':'none');}
function answerLocal(q){const fs=getFiltered(),lc=q.toLowerCase();if(/catastro|parcela|referencia/.test(lc))return state.selected?`Parcela ${state.selected.rc}: ${state.selected.site_area?Math.round(state.selected.site_area)+' m²':'sin superficie obtenida'}, construido ${state.selected.existing_built?Math.round(state.selected.existing_built)+' m²':'—'}. Datos: Catastro no protegido.`:'No hay parcela cargada.';if(/normativa|planeamiento|edific|volumen|permit/.test(lc)){const z=ZONES[document.getElementById('zone-select').value];return `Clave ${document.getElementById('zone-select').value}: edificabilidad ${z.edif??'no cargada'}, ocupación ${z.occ??'no cargada'}%, plantas ${z.floors??'no cargadas'}, altura ${z.height??'no cargada'} m. Fuente: ${z.source}.`; }if(/parking|bicicleta|comerc|oficina|servicio|salud|cine|turismo/.test(lc)){const counts={};fs.forEach(f=>counts[f.properties.category]=(counts[f.properties.category]||0)+1);return `Hay ${fs.length} registros visibles. ${Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,3).map(x=>`${x[0]} (${x[1]})`).join(', ')||'sin categorías'}. Fuente de actividad: OSM.`;}if(/3d|gemelo/.test(lc))return 'Gemelo digital: cartografía + Catastro + planeamiento + edificios 3D + escenarios. LiDAR/3D Tiles queda preparado como siguiente capa.';return `Puedo analizar ${fs.length} registros, la parcela cargada y la clave urbanística seleccionada.`;}
async function answerAgent(){const q=document.getElementById('ask').value.trim();if(!q)return;let answer=answerLocal(q);if(state.ai){try{const r=await fetch('http://localhost:11434/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:'qwen2.5:3b',stream:false,messages:[{role:'system',content:'Eres un agente SIG municipal. Solo usa el contexto entregado. No inventes normativa, distingue dato oficial, dato abierto, estimación y escenario.'},{role:'user',content:`Pregunta: ${q}\nContexto: ${JSON.stringify({parcel:state.selected,zone:ZONES[document.getElementById('zone-select').value],visible:getFiltered().length})}`}]})});if(r.ok){const j=await r.json();answer=j.message?.content||answer;}}catch{}}
document.getElementById('ask-answer').textContent=answer;}
async function connectOllama(){try{const r=await fetch('http://localhost:11434/api/tags',{signal:AbortSignal.timeout(2500)});if(!r.ok)throw 0;state.ai=true;state.aiMode='ollama';document.getElementById('ai-status').textContent='Conectada · Ollama';}catch{state.ai=false;state.aiMode='deterministic';document.getElementById('ai-status').textContent='Motor determinista · sin API';}}
function setStatus(t){document.getElementById('status').textContent=t;}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[m]));}
function getCurrentReport(){const p=state.selected,z=ZONES[document.getElementById('zone-select').value];return{generated:new Date().toISOString(),parcel:p||null,planning:{zone:document.getElementById('zone-select').value,params:z},visiblePois:getFiltered().length};}
function downloadReport(){const blob=new Blob([JSON.stringify(getCurrentReport(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sig-castelldefels-analisis.json';a.click();URL.revokeObjectURL(a.href);}
document.getElementById('search').oninput=e=>{state.q=e.target.value.toLowerCase();render();};document.getElementById('btn-fit').onclick=fitMunicipality;document.getElementById('btn-3d').onclick=()=>toggle3D();document.getElementById('btn-twin').onclick=()=>{toggle3D(true);toggleOrtho(false);document.getElementById('layer-3d').checked=true;setStatus('Gemelo 3D activado');};document.getElementById('btn-cesium').onclick=()=>window.open('./cesium.html','_blank','noopener');document.getElementById('btn-ortho').onclick=()=>toggleOrtho();document.getElementById('btn-report').onclick=downloadReport;document.getElementById('layer-poi').onchange=e=>{const v=e.target.checked?'visible':'none';['pois','pois-clusters','pois-cluster-count'].forEach(id=>map.setLayoutProperty(id,'visibility',v));};document.getElementById('layer-ortho').onchange=e=>toggleOrtho(e.target.checked);document.getElementById('layer-3d').onchange=e=>toggle3D(e.target.checked);document.getElementById('layer-norm').onchange=e=>{if(map.getLayer('norm'))map.setLayoutProperty('norm','visibility',e.target.checked?'visible':'none');};document.getElementById('layer-planning').onchange=togglePlanning;document.getElementById('layer-parcels').onchange=toggleParcelLayer;document.getElementById('btn-catastro').onclick=consultCatastro;document.getElementById('btn-catastro-map').onclick=openCatastroMap;document.getElementById('btn-generate').onclick=generateNormative;document.getElementById('btn-ask').onclick=answerAgent;document.getElementById('ask').addEventListener('keydown',e=>{if(e.key==='Enter')answerAgent();});document.getElementById('btn-ollama').onclick=connectOllama;const btnDl=document.getElementById('btn-download-analysis');if(btnDl)btnDl.onclick=downloadReport;['price','cost','eff','home-m2'].forEach(id=>document.getElementById(id).oninput=updateViability);document.getElementById('rc-input').addEventListener('keydown',e=>{if(e.key==='Enter')consultCatastro();});
